// Every value here is a literal or derived from one. Nothing is random: a seed
// that differs between runs is a seed you cannot debug against.

export const CINEMA_NAME = 'Rush Cinemas, Bengaluru';

// The demo account named in the README. The password is hashed by the seed
// before it reaches the database; it is written here in plaintext on purpose,
// because a public demo credential is not a secret.
export const DEMO_USER = {
  email: 'demo@show-rush.dev',
  password: 'demo-password',
  name: 'Demo User',
};

// Three screens, deliberately different shapes, so the seat map is exercised
// by more than one geometry.
export const SCREENS = [
  {
    name: 'Audi 1',
    seatsPerRow: 16,
    aislesAfterColumn: [4, 12],
    tierBands: [
      { tier: 'silver', rows: 4 },
      { tier: 'gold', rows: 4 },
      { tier: 'platinum', rows: 2 },
    ],
  },
  {
    name: 'Audi 2',
    seatsPerRow: 12,
    aislesAfterColumn: [6],
    tierBands: [
      { tier: 'silver', rows: 3 },
      { tier: 'gold', rows: 4 },
    ],
  },
  {
    name: 'Audi 3 (IMAX)',
    seatsPerRow: 20,
    aislesAfterColumn: [5, 15],
    tierBands: [
      { tier: 'silver', rows: 5 },
      { tier: 'gold', rows: 5 },
      { tier: 'platinum', rows: 3 },
    ],
  },
];

export const MOVIES = [
  {
    title: 'The Long Interval',
    description: 'A projectionist discovers the reel never ends.',
    durationMinutes: 142,
    language: 'English',
    certificate: 'UA',
    posterUrl: null,
  },
  {
    title: 'Monsoon Circuit',
    description: 'Two engineers chase a fault across a flooded city.',
    durationMinutes: 118,
    language: 'Hindi',
    certificate: 'U',
    posterUrl: null,
  },
  {
    title: 'Row J',
    description: 'Everything happens in one cinema row, in real time.',
    durationMinutes: 96,
    language: 'Tamil',
    certificate: 'A',
    posterUrl: null,
  },
  {
    title: 'Deadlock',
    description: 'A heist that only works if nobody waits their turn.',
    durationMinutes: 131,
    language: 'Telugu',
    certificate: 'UA',
    posterUrl: null,
  },
  {
    title: 'Idempotent',
    description: 'He relives the same payment until it settles once.',
    durationMinutes: 107,
    language: 'Kannada',
    certificate: 'U',
    posterUrl: null,
  },
];

// Paise, never rupees and never a float.
export const TIER_PRICES = {
  silver: 20000,
  gold: 32000,
  platinum: 45000,
};

const SHOW_TIMES = ['10:00', '13:30', '17:00', '20:30'];

// Five movies, four shows each: twenty shows over four days, rotating screens
// and start times. Generated by a fixed rule rather than typed out, but every
// input is a constant, so the result is identical on every run.
export const SHOW_SCHEDULE = MOVIES.flatMap((_, movieIndex) =>
  SHOW_TIMES.map((_time, slot) => ({
    movieIndex,
    screenIndex: (movieIndex + slot) % SCREENS.length,
    dayOffset: slot,
    time: SHOW_TIMES[(movieIndex + slot) % SHOW_TIMES.length],
  })),
);

// A demo that opens on an empty seat map looks broken. These are booked before
// anyone touches the app. Seats are given as row label + number; the seed
// resolves them against the seats table, so a typo fails loudly.
export const PREBOOKED_BOOKINGS = [
  { ref: 'SRDEMO001', showIndex: 0, seats: ['A1', 'A2'] },
  { ref: 'SRDEMO002', showIndex: 0, seats: ['C5', 'C6', 'C7'] },
  { ref: 'SRDEMO003', showIndex: 0, seats: ['I3', 'I4'] },
  { ref: 'SRDEMO004', showIndex: 1, seats: ['B3'] },
  { ref: 'SRDEMO005', showIndex: 5, seats: ['D8', 'D9', 'D10'] },
];

// Midnight UTC today, so re-running on the same day reproduces the same
// timestamps exactly.
export function showStartsAt(dayOffset, time) {
  const midnight = new Date();
  midnight.setUTCHours(0, 0, 0, 0);

  const [hours, minutes] = time.split(':').map(Number);
  return new Date(
    midnight.getTime() + dayOffset * 86400000 + hours * 3600000 + minutes * 60000,
  );
}
